import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { albertSans } from './fonts';

const geistSans = Geist({
  variable: "--Alexandria-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--Alexandria-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={albertSans.className}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
